# Generated by Django 4.0.4 on 2022-05-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(default=True, max_length=40)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
